#!/usr/bin/env bash
# this scripts create a key pair public and private with rsa type passphrase of betty number of bit of 4096 and name of private key school
ssh-keygen -t rsa -N betty -b 4096 -f ~/.ssh/school
